// <auto-generated />
using EFManytoMany.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFManytoMany.data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200924200643_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFManytoMany.data.Answers", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("QuestionsId");

                    b.Property<string>("Text");

                    b.HasKey("UserId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("EFManytoMany.data.Likes", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("QuestionsId");

                    b.HasKey("UserId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("EFManytoMany.data.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EFManytoMany.data.QuestionsTags", b =>
                {
                    b.Property<int>("QuestionsId");

                    b.Property<int>("TagId");

                    b.HasKey("QuestionsId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("QuestionsTags");
                });

            modelBuilder.Entity("EFManytoMany.data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EFManytoMany.data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFManytoMany.data.Answers", b =>
                {
                    b.HasOne("EFManytoMany.data.Questions", "Questions")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFManytoMany.data.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EFManytoMany.data.Likes", b =>
                {
                    b.HasOne("EFManytoMany.data.Questions", "Questions")
                        .WithMany("Likes")
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFManytoMany.data.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EFManytoMany.data.Questions", b =>
                {
                    b.HasOne("EFManytoMany.data.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EFManytoMany.data.QuestionsTags", b =>
                {
                    b.HasOne("EFManytoMany.data.Questions", "Questions")
                        .WithMany("QuestionsTags")
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EFManytoMany.data.Tag", "Tag")
                        .WithMany("QuestionsTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
